name: Update Business Database

on:
  workflow_dispatch:

  schedule:
    - cron: "0 6 * * *"


permissions:
  contents: write


jobs:

  scan:

    name: Scan Businesses

    runs-on: ubuntu-latest


    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"


      - name: Install Python packages
        run: |
          pip install -r scanner/requirements.txt


      - name: Download postcode data
        run: |
          python scanner/download_postcodes.py


      - name: Extract postcode data
        run: |
          python scanner/extract_postcodes.py


      - name: Run scanner
        run: |
          cd scanner
          python scanner.py


      - name: Save updated database
        run: |
          git config user.name "github-actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add database.json

          git commit -m "Update business database" || echo "No changes to commit"

          git push
